name: XCode Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: xcodebuild -project 'WasedaTime-Framework.xcodeproj' -scheme 'WasedaTime-Framework' -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

